"""Added desc to groups

Revision ID: 39f4509a3d83
Revises: 34b7fb4b61da
Create Date: 2021-12-29 01:14:30.282126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f4509a3d83'
down_revision = '34b7fb4b61da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('desc', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'desc')
    # ### end Alembic commands ###
