"""Changed question_quizes fk names

Revision ID: c6b35ea4e926
Revises: 70b417102d97
Create Date: 2021-12-26 21:11:57.101826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b35ea4e926'
down_revision = '70b417102d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions_quizes', sa.Column('questions_id', sa.Integer(), nullable=True))
    op.add_column('questions_quizes', sa.Column('quizes_id', sa.Integer(), nullable=True))
    op.drop_constraint('questions_quizes_questions.id_fkey', 'questions_quizes', type_='foreignkey')
    op.drop_constraint('questions_quizes_quizes.id_fkey', 'questions_quizes', type_='foreignkey')
    op.create_foreign_key(None, 'questions_quizes', 'quizes', ['quizes_id'], ['id'])
    op.create_foreign_key(None, 'questions_quizes', 'questions', ['questions_id'], ['id'])
    op.drop_column('questions_quizes', 'questions.id')
    op.drop_column('questions_quizes', 'quizes.id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions_quizes', sa.Column('quizes.id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questions_quizes', sa.Column('questions.id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions_quizes', type_='foreignkey')
    op.drop_constraint(None, 'questions_quizes', type_='foreignkey')
    op.create_foreign_key('questions_quizes_quizes.id_fkey', 'questions_quizes', 'quizes', ['quizes.id'], ['id'])
    op.create_foreign_key('questions_quizes_questions.id_fkey', 'questions_quizes', 'questions', ['questions.id'], ['id'])
    op.drop_column('questions_quizes', 'quizes_id')
    op.drop_column('questions_quizes', 'questions_id')
    # ### end Alembic commands ###
