"""Added subquestions

Revision ID: f95b843c363d
Revises: c6b35ea4e926
Create Date: 2021-12-26 21:15:51.257211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95b843c363d'
down_revision = 'c6b35ea4e926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subquestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=True),
    sa.Column('img_url', sa.String(length=255), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subquestions_answer'), 'subquestions', ['answer'], unique=False)
    op.create_index(op.f('ix_subquestions_id'), 'subquestions', ['id'], unique=False)
    op.create_index(op.f('ix_subquestions_text'), 'subquestions', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subquestions_text'), table_name='subquestions')
    op.drop_index(op.f('ix_subquestions_id'), table_name='subquestions')
    op.drop_index(op.f('ix_subquestions_answer'), table_name='subquestions')
    op.drop_table('subquestions')
    # ### end Alembic commands ###
