"""Added is public booleans to quiz and questions

Revision ID: 15737bb55cb2
Revises: ed0faeec1189
Create Date: 2021-12-28 04:44:50.733038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15737bb55cb2'
down_revision = 'ed0faeec1189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('public', sa.Boolean(), server_default='f', nullable=True))
    op.add_column('quizes', sa.Column('public', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizes', 'public')
    op.drop_column('questions', 'public')
    # ### end Alembic commands ###
