"""Added img url to questions

Revision ID: 3953d902299f
Revises: 15737bb55cb2
Create Date: 2021-12-28 05:13:57.944183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3953d902299f'
down_revision = '15737bb55cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('img_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'img_url')
    # ### end Alembic commands ###
