"""Corrections to groups many to many fks

Revision ID: 596eb409d0b8
Revises: 39f4509a3d83
Create Date: 2021-12-29 01:15:31.709928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596eb409d0b8'
down_revision = '39f4509a3d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
