"""Added questions table and many to many between questions and quizes

Revision ID: 70b417102d97
Revises: f551f7fe25a1
Create Date: 2021-12-26 21:10:09.390327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b417102d97'
down_revision = 'f551f7fe25a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outer_text', sa.String(length=400), nullable=True),
    sa.Column('questions_per_slide', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_outer_text'), 'questions', ['outer_text'], unique=False)
    op.create_table('questions_quizes',
    sa.Column('questions.id', sa.Integer(), nullable=True),
    sa.Column('quizes.id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questions.id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quizes.id'], ['quizes.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions_quizes')
    op.drop_index(op.f('ix_questions_outer_text'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
