"""Added quizes table, removed hashedpass from users

Revision ID: f551f7fe25a1
Revises: a424827f0bdd
Create Date: 2021-12-26 20:51:20.719973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f551f7fe25a1'
down_revision = 'a424827f0bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizes_id'), 'quizes', ['id'], unique=False)
    op.create_index(op.f('ix_quizes_name'), 'quizes', ['name'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_quizes_name'), table_name='quizes')
    op.drop_index(op.f('ix_quizes_id'), table_name='quizes')
    op.drop_table('quizes')
    # ### end Alembic commands ###
